name: firebase_auth_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  

dependencies:
  flutter:
    sdk: flutter 
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  injectable: ^2.5.0
  auto_route: ^10.1.0+1
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0 
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:  
    - assets/animation/
    - assets/images/

