// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBenS7uMjhTB6TEBz9Cjfw8Dgw6n2rOeHk',
    appId: '1:348230337344:web:3492a654b77df72a7030a5',
    messagingSenderId: '348230337344',
    projectId: 'ecommerce-auth-2bc16',
    authDomain: 'ecommerce-auth-2bc16.firebaseapp.com',
    storageBucket: 'ecommerce-auth-2bc16.firebasestorage.app',
    measurementId: 'G-7Y35ZFNYR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzuk05Wuex2XxpFqHA7_KJueU2YUrGAEE',
    appId: '1:348230337344:android:4b4a01a7c80aadbc7030a5',
    messagingSenderId: '348230337344',
    projectId: 'ecommerce-auth-2bc16',
    storageBucket: 'ecommerce-auth-2bc16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoiqa_oq9NwBB2R5xpnCDepK7pQHV5RQk',
    appId: '1:348230337344:ios:2108e44b5d4069297030a5',
    messagingSenderId: '348230337344',
    projectId: 'ecommerce-auth-2bc16',
    storageBucket: 'ecommerce-auth-2bc16.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoiqa_oq9NwBB2R5xpnCDepK7pQHV5RQk',
    appId: '1:348230337344:ios:2108e44b5d4069297030a5',
    messagingSenderId: '348230337344',
    projectId: 'ecommerce-auth-2bc16',
    storageBucket: 'ecommerce-auth-2bc16.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBenS7uMjhTB6TEBz9Cjfw8Dgw6n2rOeHk',
    appId: '1:348230337344:web:d861c91d3aa5a2287030a5',
    messagingSenderId: '348230337344',
    projectId: 'ecommerce-auth-2bc16',
    authDomain: 'ecommerce-auth-2bc16.firebaseapp.com',
    storageBucket: 'ecommerce-auth-2bc16.firebasestorage.app',
    measurementId: 'G-E95YJZC26G',
  );
}
